# Generated by Django 5.1.1 on 2024-10-23 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercliente',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='usercliente',
            name='password',
        ),
        migrations.AlterField(
            model_name='usercliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
